# Generated by Django 6.1 on 2026-09-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField(help_text='The content evaluated by the Blocking Engine.')),
                ('Action', models.CharField(choices=[('ALLOW', 'Allow'), ('BLOCK', 'Block')], help_text='The final action taken by the Blocking Engine.', max_length=10)),
                ('Reason', models.CharField(choices=[('OFFENSIVE_CONTENT', 'Offensive content'), ('SAFE_CONTENT', 'Safe content'), ('UNKNOWN', 'Unknown')], help_text='The reason behind the blocking decision.', max_length=50)),
                ('Confidence', models.FloatField(blank=True, help_text='Confidence returned by the detection component.', null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the decision was created.')),
            ],
        ),
    ]
